# Generated by Django 4.1.2 on 2023-03-30 06:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voter",
            name="voted_in",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="voters", to="api.election"
            ),
        ),
    ]
