# Generated by Django 4.1.2 on 2023-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_election_options_election_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="number_of_votes",
            field=models.IntegerField(default=0),
        ),
    ]
