# Generated by Django 4.1.2 on 2023-04-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_election_number_of_votes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="election",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
